### ISSUE TITLE
To ensure that the code across our devices are homogenous, and thus easier to read, enable automatic code formatting.

### ISSUE THREAD

**Issue by zqueamish** [ITU-BDSA23-GROUP19/Chirp#12]
Session 03: 1.c
As a developer, my code will be easier to compare to my team members code.

Acceptance Criteria:
- On your device, enable the "Format On Save" by setting the "editor.formatOnSave" to true. You can do this manually in settings, by searching for "Format on save" and enable it.

**Comment by PatrickHJessen** [comment]
Done
